#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 10, 2020 12:19:36 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global lblfonrttools
    lblfonrttools = tk.StringVar()
    lblfonrttools.set('FONT TOOLS')
    global lblpagetools
    lblpagetools = tk.StringVar()
    lblpagetools.set('Page format tools')
    global spinbox
    spinbox = tk.StringVar()
    spinbox = 14
    global combobox
    combobox = tk.IntVar()
    global selectedButton
    selectedButton = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import maintktscreen
    maintktscreen.vp_start_gui()




